






spring.application.name=SmartRahi

# ------------------ Database ------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ------------------ JPA / Hibernate ------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ------------------ Logging ------------------
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc=DEBUG

# ------------------ Admin Secret ------------------
ADMIN_SECRET=${ADMIN_SECRET}

# ------------------ JWT ------------------

app.jwt.secret=${JWT_SECRET} // jwt secre key 
app.jwt.access-token-ms=900000
app.jwt.refresh-token-ms=2592000000

# ------------------ Hikari ------------------
spring.datasource.hikari.keepalive-time=1200000

# ------------------ Swagger ------------------
springdoc.swagger-ui.path=/swagger-ui.html

# ------------------ Server ------------------
server.port=${PORT:8080}
