spring.application.name=SmartRahi

# PostgreSQL DB (Supabase)
# spring.datasource.url=jdbc:postgresql://db.ltjrqswbvioshaspfler.supabase.co:5432/postgres?sslmode=require
# #spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
# spring.datasource.username=postgres
# spring.datasource.password=0Cuq054bFn1sVsBa
# spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
# spring.datasource.username=postgres.veyrbwzexvsrqawlaysl
# spring.datasource.password=smart-rahi-db
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc=DEBUG

# ------------------ Database ------------------
spring.datasource.url=jdbc:postgresql://ep-round-hat-adm5ijmy-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ktN1BcX0lyQj
spring.datasource.driver-class-name=org.postgresql.Driver

##spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.veyrbwzexvsrqawlaysl
#spring.datasource.password=smart-rahi-db

# ------------------ JPA / Hibernate ------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true



ADMIN_SECRET=SuperSecret123!


# JWT configuration
app.jwt.secret=8f9a1b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5061728394050607080
 # 15 minutes for normal users
app.jwt.access-token-ms=900000
# 30 days for normal users
app.jwt.refresh-token-ms=2592000000

# Ping idle connections every 2 minutes to keep them alive
spring.datasource.hikari.keepalive-time=1200000
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#for render
server.port=${PORT:8080}

